[package]
name = "csv_validator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0"}

[profile.release]
debug = true
